# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='author_id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='msg_user',
            new_name='msg_user_id',
        ),
    ]
